/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.lob.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.lob.api.internal.OptionalNullable;

/**
 * This is a model class for CardEditable type.
 */
public class CardEditable {
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private OptionalNullable<String> description;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private SizeEnum size;
    private Object front;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Object back;

    /**
     * Default constructor.
     */
    public CardEditable() {
        size = SizeEnum.ENUM_2125X3375;
    }

    /**
     * Initialization constructor.
     * @param  front  Object value for front.
     * @param  description  String value for description.
     * @param  size  SizeEnum value for size.
     * @param  back  Object value for back.
     */
    public CardEditable(
            Object front,
            String description,
            SizeEnum size,
            Object back) {
        this.description = OptionalNullable.of(description);
        this.size = size;
        this.front = front;
        this.back = back;
    }

    /**
     * Internal initialization constructor.
     */
    protected CardEditable(Object front, OptionalNullable<String> description, SizeEnum size,
            Object back) {
        this.description = description;
        this.size = size;
        this.front = front;
        this.back = back;
    }

    /**
     * Internal Getter for Description.
     * Description of the card.
     * @return Returns the Internal String
     */
    @JsonGetter("description")
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetDescription() {
        return this.description;
    }

    /**
     * Getter for Description.
     * Description of the card.
     * @return Returns the String
     */
    public String getDescription() {
        return OptionalNullable.getFrom(description);
    }

    /**
     * Setter for Description.
     * Description of the card.
     * @param description Value for String
     */
    @JsonSetter("description")
    public void setDescription(String description) {
        this.description = OptionalNullable.of(description);
    }

    /**
     * UnSetter for Description.
     * Description of the card.
     */
    public void unsetDescription() {
        description = null;
    }

    /**
     * Getter for Size.
     * The size of the card
     * @return Returns the SizeEnum
     */
    @JsonGetter("size")
    public SizeEnum getSize() {
        return size;
    }

    /**
     * Setter for Size.
     * The size of the card
     * @param size Value for SizeEnum
     */
    @JsonSetter("size")
    public void setSize(SizeEnum size) {
        this.size = size;
    }

    /**
     * Getter for Front.
     * A PDF template for the front of the card
     * @return Returns the Object
     */
    @JsonGetter("front")
    public Object getFront() {
        return front;
    }

    /**
     * Setter for Front.
     * A PDF template for the front of the card
     * @param front Value for Object
     */
    @JsonSetter("front")
    public void setFront(Object front) {
        this.front = front;
    }

    /**
     * Getter for Back.
     * A PDF template for the back of the card
     * @return Returns the Object
     */
    @JsonGetter("back")
    public Object getBack() {
        return back;
    }

    /**
     * Setter for Back.
     * A PDF template for the back of the card
     * @param back Value for Object
     */
    @JsonSetter("back")
    public void setBack(Object back) {
        this.back = back;
    }

    /**
     * Converts this CardEditable into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CardEditable [" + "front=" + front + ", description=" + description + ", size="
                + size + ", back=" + back + "]";
    }

    /**
     * Builds a new {@link CardEditable.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CardEditable.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(front)
                .size(getSize())
                .back(getBack());
        builder.description = internalGetDescription();
        return builder;
    }

    /**
     * Class to build instances of {@link CardEditable}.
     */
    public static class Builder {
        private Object front;
        private OptionalNullable<String> description;
        private SizeEnum size = SizeEnum.ENUM_2125X3375;
        private Object back;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  front  Object value for front.
         */
        public Builder(Object front) {
            this.front = front;
        }

        /**
         * Setter for front.
         * @param  front  Object value for front.
         * @return Builder
         */
        public Builder front(Object front) {
            this.front = front;
            return this;
        }

        /**
         * Setter for description.
         * @param  description  String value for description.
         * @return Builder
         */
        public Builder description(String description) {
            this.description = OptionalNullable.of(description);
            return this;
        }

        /**
         * UnSetter for description.
         * @return Builder
         */
        public Builder unsetDescription() {
            description = null;
            return this;
        }

        /**
         * Setter for size.
         * @param  size  SizeEnum value for size.
         * @return Builder
         */
        public Builder size(SizeEnum size) {
            this.size = size;
            return this;
        }

        /**
         * Setter for back.
         * @param  back  Object value for back.
         * @return Builder
         */
        public Builder back(Object back) {
            this.back = back;
            return this;
        }

        /**
         * Builds a new {@link CardEditable} object using the set fields.
         * @return {@link CardEditable}
         */
        public CardEditable build() {
            return new CardEditable(front, description, size, back);
        }
    }
}
