/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.lob.api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Metadata type.
 */
public class Metadata {
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Object metadata;

    /**
     * Default constructor.
     */
    public Metadata() {
    }

    /**
     * Initialization constructor.
     * @param  metadata  Object value for metadata.
     */
    public Metadata(
            Object metadata) {
        this.metadata = metadata;
    }

    /**
     * Getter for Metadata.
     * @return Returns the Object
     */
    @JsonGetter("metadata")
    public Object getMetadata() {
        return metadata;
    }

    /**
     * Setter for Metadata.
     * @param metadata Value for Object
     */
    @JsonSetter("metadata")
    public void setMetadata(Object metadata) {
        this.metadata = metadata;
    }

    /**
     * Converts this Metadata into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Metadata [" + "metadata=" + metadata + "]";
    }

    /**
     * Builds a new {@link Metadata.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Metadata.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .metadata(getMetadata());
        return builder;
    }

    /**
     * Class to build instances of {@link Metadata}.
     */
    public static class Builder {
        private Object metadata;



        /**
         * Setter for metadata.
         * @param  metadata  Object value for metadata.
         * @return Builder
         */
        public Builder metadata(Object metadata) {
            this.metadata = metadata;
            return this;
        }

        /**
         * Builds a new {@link Metadata} object using the set fields.
         * @return {@link Metadata}
         */
        public Metadata build() {
            return new Metadata(metadata);
        }
    }
}
