/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.lob.api.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * OrientationEnum to be used.
 */
public enum OrientationEnum {
    HORIZONTAL,

    VERTICAL;


    private static TreeMap<String, OrientationEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        HORIZONTAL.value = "horizontal";
        VERTICAL.value = "vertical";

        valueMap.put("horizontal", HORIZONTAL);
        valueMap.put("vertical", VERTICAL);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static OrientationEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of OrientationEnum values to list of string values.
     * @param toConvert The list of OrientationEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<OrientationEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (OrientationEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 