/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.lob.api.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * SizeEnum to be used.
 */
public enum SizeEnum {
    ENUM_3375X2125,

    ENUM_2125X3375;


    private static TreeMap<String, SizeEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        ENUM_3375X2125.value = "3.375x2.125";
        ENUM_2125X3375.value = "2.125x3.375";

        valueMap.put("3.375x2.125", ENUM_3375X2125);
        valueMap.put("2.125x3.375", ENUM_2125X3375);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static SizeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of SizeEnum values to list of string values.
     * @param toConvert The list of SizeEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<SizeEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (SizeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 