/*
 * LobLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.lob.api.models;

import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * TheStatusOfTheCardEnum to be used.
 */
public enum TheStatusOfTheCardEnum {
    PROCESSED,

    RENDERED;


    private static TreeMap<String, TheStatusOfTheCardEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        PROCESSED.value = "processed";
        RENDERED.value = "rendered";

        valueMap.put("processed", PROCESSED);
        valueMap.put("rendered", RENDERED);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    @com.fasterxml.jackson.annotation.JsonCreator
    public static TheStatusOfTheCardEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @com.fasterxml.jackson.annotation.JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of TheStatusOfTheCardEnum values to list of string values.
     * @param toConvert The list of TheStatusOfTheCardEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<TheStatusOfTheCardEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (TheStatusOfTheCardEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 